[package]
name = "expecters-macros"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = "2.0.114"

[lib]
proc-macro = true
