[package]
name = "expecters-bevy"
version = "0.1.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = [
    "bevy_mesh",
] }
expecters = { version = "0.1.0", path = "../.." }
